### ISSUE TITLE
HP ILO Adapter installed v1.0.5 but installs 0.0.1 

### ISSUE THREAD

**Issue by niceguy0815** [SebastianSchultz/ioBroker.hp-ilo#17]
Hi,
i have installed the HP ILO Adapter installed v1.0.5 but it installs in v 0.0.1 now i see a Adapter Update to 1.0.5 it runns but after Update version is still 0.0.1 and wants to update the Adapter.

The Installation shows no error.
Is the version number in 1.0.5 wrong (0.0.1)
So iobroker wants to update it over and over again?
Ore do i need somthing special to install 1.0.5?
`$ ./iobroker upgrade hp-ilo Update hp-ilo from @0.0.1 to @1.0.5 NPM version: 6.13.4 npm install iobroker.hp-ilo@1.0.5 --loglevel error --prefix "/opt/iobroker" (System call) upload [3] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/words.js words.js application/javascript upload [2] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/index_m.html index_m.html text/html upload [1] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/index.html index.html text/html upload [0] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/hp-ilo.png hp-ilo.png image/png Adapter "hp-ilo" updated process exited with code 0 `

<img width="1112" alt="iobrokerhpilo" src="https://user-images.githubusercontent.com/43955022/75773337-fc00d780-5d4d-11ea-8653-e8ebc4fb560c.png">
<img width="317" alt="iobrokerhpilo2" src="https://user-images.githubusercontent.com/43955022/75773458-3c605580-5d4e-11ea-9f45-9691dd159006.png">

**Comment by SebastianSchultz** [comment]
Hello,

I can't reproduce that. I've removed the adapter itself from my installation and installed it via the GitHub Icon. It shows me as installed and available version 1.0.5.

**Comment by niceguy0815** [comment]
Tested it several times remove the adapter and try to installit or Update ist:

It says Update to 1.0.5 but after the update still shows the Update in iobroker and after fresh new installation shows the 1.0.5 update too.
I there a way to debug the plugin installation on my system?

**Comment by SebastianSchultz** [comment]
Sorry that's not a problem by the adapter itself. I can't reproduce that even not on a fresh iobroker install.
Do you have the "latest" repository set in the iobroker config?

The only way to debug an adapter installation is the iobroker debug log or the npm log.

**Comment by niceguy0815** [comment]
hi,
yes it is latest repo. It is a 1 Month old fresh installed Ubuntu 18.04 VW on an esx Host. And the esx Host is the HP Server.
When i say Update in GUI or via SSH it says OK:
<img width="671" alt="iobroker-hpilo" src="https://user-images.githubusercontent.com/43955022/76301236-3a524580-62be-11ea-98be-5ac9a1e14069.png">

**Comment by SebastianSchultz** [comment]
What If you uninstall the adapter completely and re-install via Github link?

**Comment by niceguy0815** [comment]
Hi what do you mean with "Github link"?

**Comment by SebastianSchultz** [comment]
Uninstall the adapter completely. After that you can use the icon no. 5 ([https://www.iobroker.net/#de/documentation/admin/adapter.md?die-icons-im-einzelnen](url) and enter the URL https://github.com/SebastianSchultz/ioBroker.hp-ilo to install the adapter direct from GitHub source.

**Comment by niceguy0815** [comment]
Hi,
first thanks for the tip. 
But ends the same it shows as 0.0.1 :(
<img width="1115" alt="iobroker-hpeilo" src="https://user-images.githubusercontent.com/43955022/76444093-bd10f880-63c3-11ea-8d39-ad21d7ba4c60.png">

**Comment by vr6syncro** [comment]
have the same problems since a few month
