### ISSUE TITLE
Did't see temperature

### ISSUE THREAD

**Issue by Anzic23** [SebastianSchultz/ioBroker.hp-ilo#20]
the adapter creates objects in the system.adapter.hp-ilo.0 folder. I have to enable the display of system objects. And they have no temperature.

**Comment by SebastianSchultz** [comment]
Sorry, I can't reproduce that :(
Did you tried to reinstall the adapter completely (delete the old instance & adapter and reinstall it)?

**Comment by Anzic23** [comment]
update ilo to latest version. Now it's OK!
