### ISSUE TITLE
Ilo Firmware Version 1.94 ILO 3 not working

### ISSUE THREAD

**Issue by HobboRobin** [SebastianSchultz/ioBroker.hp-ilo#22]
Servus or Hello :D

I know that the Ilo Adpater is not made for Version 1.94 but is it possible to expand it to this function or what is the problem ?

Best regards Robin

**Comment by SebastianSchultz** [comment]
Hello Robin,

ILO1 uses another API für the thermal information.
I don't have information about this API so that I can't test/develop the support for ILO1.

I'm sorry... :(
