### ISSUE TITLE
Add Adapter-testing (travis-ci at least)

### ISSUE THREAD

**Issue by Apollon77** [SebastianSchultz/ioBroker.hp-ilo#4]

**Comment by SebastianSchultz** [comment]
Do you have any documentation on how doing this?! Sorry I'm a badly newbie in Github :)

**Comment by Apollon77** [comment]
Basically from https://github.com/ioBroker/ioBroker.template/ get:
- test directory
- travis.yml (Linux,Macos), appveyor.yml for windows
- scripts->test in package.json

Then signup with travis-ci.org with your github account and activate the project. make a commit

**Comment by SebastianSchultz** [comment]
Implemented in first release v.1.0.0
