### ISSUE TITLE
Adapter liefert keine Max werte

### ISSUE THREAD

**Issue by vr6syncro** [SebastianSchultz/ioBroker.hp-ilo#5]
Moin an sich bekommt er seine Werte aber die Max werte will er sich nicht ziehen. 
auch der Infos Status steht immer auf false
`

  |   |   |  
-- | -- | -- | --
hp-ilo.0 | 2018-04-20 15:56:32.921 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.921 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.920 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.920 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.920 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.920 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.919 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.919 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.919 | debug | Current Reading > 0
hp-ilo.0 | 2018-04-20 15:56:32.461 | info | Ready. Configured HP ILO: 192.168.2.8
hp-ilo.0 | 2018-04-20 15:56:32.459 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.hp-ilo, node: v6.14.1
hp-ilo.0 | 2018-04-20 15:56:32.354 | debug | statesDB connected
hp-ilo.0 | 2018-04-20 15:56:32.335 | debug | objectDB connected
hp-ilo.0 | 2018-04-20 15:56:29.993 | info | terminating

`

**Comment by SebastianSchultz** [comment]
Hallo,

das Verhalten ist normal. Die MAX-Werte vergibt der User selbst.
Hier wird der Schwellenwert angegeben, ab wann ein Alarm erfolgen soll.

**Comment by vr6syncro** [comment]
ok alles klar
