### ISSUE TITLE
Adapter legt keine Objekte an

### ISSUE THREAD

**Issue by tigus309** [SebastianSchultz/ioBroker.hp-ilo#8]
Hallo, bei mir legt der Adapter keine Objekte an. Neustart / Neuinstallation bringen nichts. Zugangsdaten sind defintiv richtig, Adapter wird grün.

**Comment by SebastianSchultz** [comment]
Hallo,

welche ILO Version nutzt Du?
Ich nutze die ILO Firmware 2.55 auf meinem HP Microserver. Da funktioniert das einwandfrei.
Steht im Debug-Log irgendwas?
Hast Du in der Adapter-Konfiguration einen Hostnamen oder eine IP-Adresse eingetragen?

**Comment by tigus309** [comment]
Hallo, Asche auf mein Haupt... ILO4 heisst noch lange nicht Version 4... ;) Habe jetzt ein ILO-Update gemacht und es läuft alles wie es soll. Vielen Dank!

Gruss Daniel
